spring.datasource.url=jdbc:postgresql://dpg-d96gtguq1p3s73c4k3g0-a:5432/todo_db_y6f33
spring.datasource.username=todo_db_y6f3_user
spring.datasource.password=rwEAvBr0Jus1uDgwFOZ8eSaESeRtwy2i

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=PORT:8080
spring.application.name=HelloWorld

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
