spring.datasource.url=${postgresql://todo_db_y6f3_user:rwEAvBr0Jus1uDgwFOZ8eSaESeRtwy2i@dpg-d96gtguq1p3s73c4k3g0-a/todo_db_y6f3}
spring.datasource.username=${todo_db_y6f3_user}
spring.datasource.password=${rwEAvBr0Jus1uDgwFOZ8eSaESeRtwy2i}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8081}
