spring.application.name=HelloWorld

server.port=8081

spring.datasource.url=jdbc:postgresql://host.docker.internal:5433/todo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Tamilarasi367@

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=1234
